# fly.toml app configuration file generated for joybox-new on 2023-06-09T01:11:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joybox-new"
primary_region = "yyz"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
